name: Deploy Duck-UI Docs to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - "docs/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: |
      (!contains(github.event.head_commit.message, 'no-docs') && !contains(github.event.head_commit.message, 'release-only') && !contains(github.event.head_commit.message, 'docker-only')) || 
      contains(github.event.head_commit.message, 'docs-only')
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: |
          cd docs
          bun install

      - name: Build website
        run: |
          cd docs
          bun run build

      - name: Add .nojekyll file
        run: touch docs/build/.nojekyll

      - name: Create CNAME file
        run: echo "duckui.com" > docs/build/CNAME

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GHCR_PAT }}
          publish_dir: ./docs/build
          user_name: ${{ secrets.GIT_USER_NAME }}
          user_email: ${{ secrets.GIT_USER_EMAIL }}